### ISSUE TITLE
Misleading schematic

### ISSUE THREAD

**Issue by owain68** [vincent-herlemont/next-aws-lambda-webpack-plugin#22]
The schematic is somewhat misleading.  https://github.com/vincent-herlemont/next-aws-lambda-webpack-plugin/blob/master/assets/cloud-front-distribution-example.png?raw=true

`parameter.js` in fact sits behind the API Gateway as a ƛ resolver and Cloudfront is just serving the static resources via S3.  There is no connection from CF to parameter.js at all and certainly isn't in the yellow cloud front.

Might be an idea to use one of the AWS diagramming tools to draw out what's actually created.

**Comment by vincent-herlemont** [comment]
`parameter.js` allows to configure the behavior of lambda@edge function, and [lambda@edge function stay in cloudfront](https://aws.amazon.com/lambda/edge/). This one is triggered on [Origin Request event](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-cloudfront-trigger-events.html) and take care to "route" the request towards s3 (for static content) or API-Gateway (for SSR rendering). 

The tutorial are not very clear and some additional informations will be added.

PS: the tutorial have as inspiration this [AWS article](https://aws.amazon.com/blogs/networking-and-content-delivery/dynamically-route-viewer-requests-to-any-origin-using-lambdaedge/), maybe it's useful for understand how the lambda@edge function can to route requests.

**Comment by owain68** [comment]
@vincent yes the docs are generally unclear.  The AWS article articulates a use case we have, namely detecting web crawlers and presenting more helpful content to them without creating sessions and so forth.  These pages can all be SSRd. A quick win.  Thanks for following up.
