### ISSUE TITLE
Why does this work with Next.js 10?

### ISSUE THREAD

**Issue by lcswillems** [vincent-herlemont/next-aws-lambda-webpack-plugin#41]
Hi Vincent,

Your webpack plugin looks really interesting! However, I am surprised to see it works with Next.js 10 whereas you say using "next-aws-lambda" under the hood and they claim to support Next.js 9 only.

How is it possible your webpack plugin is working with Next.js 10?

**Comment by vincent-herlemont** [comment]
Hello @lcswillems,

The integration [test](https://github.com/vincent-herlemont/next-aws-lambda-webpack-plugin/blob/master/tests/integration.js) that you mention, can not say if all functionalities of Next.js works with AWS this job is delegate to [next-aws-lambda](https://www.npmjs.com/package/next-aws-lambda) plugin. 

However [next-aws-lambda-webpack-plugin](https://github.com/vincent-herlemont/next-aws-lambda-webpack-plugin) works with Next.js 10, you can follow the example in the folder [/example](https://github.com/vincent-herlemont/next-aws-lambda-webpack-plugin/tree/master/example), this is an complete example with Next.js 10.0.5.

Can you give more information about this issue ? (logs errors, context etc.)

**Comment by lcswillems** [comment]
What do you mean by "next-aws-lambda-webpack-plugin" works with Next.js 10? If I take a Next.js 10 project and use your plugin, put it on AWS, will it work?

**Comment by vincent-herlemont** [comment]
I don't know your project but yes it works.

**Comment by lcswillems** [comment]
Ok thanks for your answer @vincent-herlemont !
